/* Generated by Yosys 0.40+33 (git sha1 c3ae33da3, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "controlador.v:8.1-197.10" *)
module controlador(clock, reset, sensor_a, sensor_b, pin_validation, pin, alarma_pin_incorrecto, alarma_bloqueo, senal_abrir_compuerta, senal_cerrar_compuerta);
  (* src = "controlador.v:64.1-191.4" *)
  wire _000_;
  (* src = "controlador.v:64.1-191.4" *)
  wire _001_;
  (* src = "controlador.v:64.1-191.4" *)
  wire _002_;
  (* src = "controlador.v:64.1-191.4" *)
  wire [2:0] _003_;
  (* src = "controlador.v:64.1-191.4" *)
  wire [4:0] _004_;
  (* src = "controlador.v:64.1-191.4" *)
  wire [2:0] _005_;
  (* src = "controlador.v:64.1-191.4" *)
  wire _006_;
  (* src = "controlador.v:64.1-191.4" *)
  wire [2:0] _007_;
  (* src = "controlador.v:64.1-191.4" *)
  wire [2:0] _008_;
  (* src = "controlador.v:64.1-191.4" *)
  wire [2:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire [1:0] _089_;
  wire [1:0] _090_;
  wire [1:0] _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire [2:0] _095_;
  wire [2:0] _096_;
  wire _097_;
  wire [15:0] _098_;
  wire [7:0] _099_;
  wire [3:0] _100_;
  wire [2:0] _101_;
  wire _102_;
  wire [2:0] _103_;
  wire _104_;
  wire [2:0] _105_;
  wire _106_;
  wire [3:0] _107_;
  wire [1:0] _108_;
  wire [1:0] _109_;
  wire [2:0] _110_;
  wire _111_;
  (* src = "controlador.v:109.22-109.40" *)
  wire _112_;
  (* src = "controlador.v:117.22-117.26" *)
  wire _113_;
  (* src = "controlador.v:114.22-114.58" *)
  wire _114_;
  (* src = "controlador.v:95.23-95.44" *)
  wire _115_;
  (* src = "controlador.v:133.37-133.46" *)
  wire _116_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [17:0] _117_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [17:0] _118_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [5:0] _119_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _120_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _121_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _122_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:575.21-575.22" *)
  wire _123_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire _124_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [9:0] _125_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [9:0] _126_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [4:0] _127_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _128_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _129_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _130_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _131_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _132_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4" *)
  wire [31:0] _133_;
  wire _134_;
  wire _135_;
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _136_;
  (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _137_;
  (* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _138_;
  (* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _139_;
  (* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _140_;
  (* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _141_;
  (* src = "controlador.v:48.6-48.7" *)
  wire Y;
  (* src = "controlador.v:26.35-26.49" *)
  output alarma_bloqueo;
  reg alarma_bloqueo;
  (* src = "controlador.v:26.12-26.33" *)
  output alarma_pin_incorrecto;
  reg alarma_pin_incorrecto;
  (* src = "controlador.v:22.7-22.12" *)
  input clock;
  wire clock;
  (* src = "controlador.v:38.11-38.12" *)
  wire [4:0] i;
  (* src = "controlador.v:44.11-44.16" *)
  wire [4:0] nxt_i;
  (* src = "controlador.v:41.11-41.20" *)
  wire [2:0] nxt_state;
  (* src = "controlador.v:35.11-35.20" *)
  reg [2:0] old_state;
  (* src = "controlador.v:23.13-23.16" *)
  input [7:0] pin;
  wire [7:0] pin;
  (* src = "controlador.v:22.41-22.55" *)
  input pin_validation;
  wire pin_validation;
  (* src = "controlador.v:22.14-22.19" *)
  input reset;
  wire reset;
  (* src = "controlador.v:27.12-27.33" *)
  output senal_abrir_compuerta;
  reg senal_abrir_compuerta;
  (* src = "controlador.v:27.35-27.57" *)
  output senal_cerrar_compuerta;
  reg senal_cerrar_compuerta;
  (* src = "controlador.v:22.21-22.29" *)
  input sensor_a;
  wire sensor_a;
  (* src = "controlador.v:22.31-22.39" *)
  input sensor_b;
  wire sensor_b;
  (* src = "controlador.v:32.11-32.16" *)
  wire [2:0] state;
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_027_) alarma_pin_incorrecto = _000_;
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_038_) alarma_bloqueo = _123_;
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_039_) senal_abrir_compuerta = _001_;
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_044_) senal_cerrar_compuerta = _002_;
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_047_) old_state[0] = state[0];
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_047_) old_state[1] = state[1];
  (* src = "controlador.v:64.1-191.4" *)
  always @*
    if (!_047_) old_state[2] = state[2];
  (* src = "controlador.v:52.1-60.4" *)
  DFF _149_ (
    .C(clock),
    .D(_069_),
    .Q(state[0])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _150_ (
    .C(clock),
    .D(_071_),
    .Q(state[1])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _151_ (
    .C(clock),
    .D(_073_),
    .Q(state[2])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _152_ (
    .C(clock),
    .D(_075_),
    .Q(i[0])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _153_ (
    .C(clock),
    .D(_077_),
    .Q(i[1])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _154_ (
    .C(clock),
    .D(_079_),
    .Q(i[2])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _155_ (
    .C(clock),
    .D(_081_),
    .Q(i[3])
  );
  (* src = "controlador.v:52.1-60.4" *)
  DFF _156_ (
    .C(clock),
    .D(_083_),
    .Q(i[4])
  );
  assign _068_ = _015_ ? nxt_state[0] : state[0];
  assign _070_ = _015_ ? nxt_state[1] : state[1];
  assign _072_ = _015_ ? nxt_state[2] : state[2];
  assign _074_ = _016_ ? nxt_i[0] : i[0];
  assign _076_ = _016_ ? nxt_i[1] : i[1];
  assign _078_ = _016_ ? nxt_i[2] : i[2];
  assign _080_ = _016_ ? nxt_i[3] : i[3];
  assign _082_ = _016_ ? nxt_i[4] : i[4];
  assign _069_ = reset ? 1'h0 : _068_;
  assign _071_ = reset ? 1'h0 : _070_;
  assign _073_ = reset ? 1'h0 : _072_;
  assign _075_ = reset ? 1'h0 : _074_;
  assign _077_ = reset ? 1'h0 : _076_;
  assign _079_ = reset ? 1'h0 : _078_;
  assign _081_ = reset ? 1'h0 : _080_;
  assign _083_ = reset ? 1'h0 : _082_;
  assign _059_ = ~pin[5];
  assign _060_ = ~pin[4];
  assign _061_ = ~pin[3];
  assign _062_ = ~pin[2];
  assign _063_ = ~pin[0];
  assign _132_[4] = ~i[4];
  assign _132_[3] = ~i[3];
  assign _132_[2] = ~i[2];
  assign _064_ = ~state[1];
  assign _065_ = ~state[0];
  assign _129_[0] = ~i[0];
  assign _066_ = ~state[2];
  assign _067_ = ~sensor_b;
  assign _006_ = ~Y;
  assign _133_[31] = ~_131_[31];
  assign _000_ = _119_[2] |(* src = {0{1'b0}} *)  _119_[4];
  assign _121_[1] = _000_ |(* src = {0{1'b0}} *)  _119_[1];
  assign _022_ = _084_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  _066_;
  assign _023_ = _085_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  _066_;
  assign _086_ = state[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  _064_;
  assign _021_ = _086_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  state[2];
  assign _087_ = _065_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  _064_;
  assign _019_ = _087_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  state[2];
  assign _085_ = _065_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  state[1];
  assign _018_ = _085_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  state[2];
  assign _088_ = _048_ |(* src = "controlador.v:64.1-191.4" *)  _049_;
  assign _027_ = _088_ |(* src = "controlador.v:64.1-191.4" *)  _050_;
  assign _089_[1] = _053_ |(* src = "controlador.v:64.1-191.4" *)  _054_;
  assign _038_ = _089_[0] |(* src = "controlador.v:64.1-191.4" *)  _089_[1];
  assign _089_[0] = _051_ |(* src = "controlador.v:64.1-191.4" *)  _052_;
  assign _039_ = _089_[0] |(* src = "controlador.v:64.1-191.4" *)  _054_;
  assign _016_ = _000_ &(* src = {0{1'b0}} *)  _014_;
  assign _014_ = _006_ |(* src = {0{1'b0}} *)  _019_;
  assign _091_[0] = _013_ &(* src = {0{1'b0}} *)  _012_;
  assign _091_[1] = _011_ &(* src = {0{1'b0}} *)  _010_;
  assign _015_ = _091_[0] &(* src = {0{1'b0}} *)  _091_[1];
  assign _013_ = _109_[0] |(* src = {0{1'b0}} *)  _022_;
  assign _092_ = Y |(* src = {0{1'b0}} *)  _110_[1];
  assign _012_ = _092_ |(* src = {0{1'b0}} *)  _021_;
  assign _093_ = Y |(* src = {0{1'b0}} *)  _109_[0];
  assign _011_ = _093_ |(* src = {0{1'b0}} *)  _019_;
  assign _094_ = Y |(* src = {0{1'b0}} *)  _067_;
  assign _010_ = _094_ |(* src = {0{1'b0}} *)  _023_;
  assign _090_[0] = _052_ |(* src = "controlador.v:64.1-191.4" *)  _054_;
  assign _090_[1] = _055_ |(* src = "controlador.v:64.1-191.4" *)  _056_;
  assign _095_[2] = _057_ |(* src = "controlador.v:64.1-191.4" *)  _058_;
  assign _044_ = _090_[0] |(* src = "controlador.v:64.1-191.4" *)  _090_[1];
  assign _047_ = _044_ |(* src = "controlador.v:64.1-191.4" *)  _095_[2];
  assign _122_[0] = _119_[0] |(* src = {0{1'b0}} *)  _119_[3];
  assign _096_[0] = _119_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _119_[1];
  assign _096_[1] = _119_[2] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _119_[3];
  assign _096_[2] = _119_[4] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _119_[5];
  assign _097_ = _096_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _096_[1];
  assign _136_ = _097_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _096_[2];
  assign _113_ = _134_ |(* src = {0{1'b0}} *)  _100_[0];
  assign _128_[1] = i[0] &(* src = "controlador.v:117.22-117.26" *)  i[1];
  assign _099_[0] = _128_[1] &(* src = "controlador.v:117.22-117.26" *)  _098_[1];
  assign _100_[0] = _099_[0] &(* src = "controlador.v:117.22-117.26" *)  _132_[4];
  assign _127_[4] = _126_[4] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _126_[9];
  assign _127_[3] = _126_[3] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _126_[8];
  assign _127_[2] = _126_[2] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _126_[7];
  assign _127_[1] = _126_[1] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _126_[6];
  assign _127_[0] = _126_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _126_[5];
  assign _101_[0] = _118_[1] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[3];
  assign _101_[1] = _118_[6] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[9];
  assign _101_[2] = _118_[12] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[15];
  assign _102_ = _101_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _101_[1];
  assign _120_[0] = _102_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _101_[2];
  assign _103_[0] = _118_[1] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[4];
  assign _103_[1] = _118_[7] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[10];
  assign _103_[2] = _118_[13] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[16];
  assign _104_ = _103_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _103_[1];
  assign _120_[1] = _104_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _103_[2];
  assign _105_[0] = _118_[2] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[5];
  assign _105_[1] = _118_[8] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[11];
  assign _105_[2] = _118_[14] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _118_[17];
  assign _106_ = _105_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _105_[1];
  assign _120_[2] = _106_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _105_[2];
  assign _124_ = _121_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _121_[1];
  assign _137_ = _122_[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _121_[1];
  assign _107_[0] = _063_ |(* src = "controlador.v:162.21-162.39" *)  pin[1];
  assign _107_[1] = _062_ |(* src = "controlador.v:162.21-162.39" *)  _061_;
  assign _107_[2] = _060_ |(* src = "controlador.v:162.21-162.39" *)  _059_;
  assign _107_[3] = pin[6] |(* src = "controlador.v:162.21-162.39" *)  pin[7];
  assign _108_[0] = _107_[0] |(* src = "controlador.v:162.21-162.39" *)  _107_[1];
  assign _108_[1] = _107_[2] |(* src = "controlador.v:162.21-162.39" *)  _107_[3];
  assign _111_ = _108_[0] |(* src = "controlador.v:162.21-162.39" *)  _108_[1];
  assign _084_ = state[0] |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  state[1];
  assign _017_ = _084_ |(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *)  state[2];
  assign _119_[1] = ~(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) _022_;
  assign _119_[0] = ~(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) _023_;
  assign _119_[3] = ~(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) _021_;
  assign _119_[5] = ~(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) _017_;
  assign _119_[2] = ~(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) _019_;
  assign _119_[4] = ~(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) _018_;
  assign _112_ = ~(* src = "controlador.v:162.21-162.39" *) _111_;
  assign _115_ = sensor_a &(* src = "controlador.v:95.23-95.44" *)  _067_;
  assign _110_[1] = sensor_b &(* src = "controlador.v:133.25-133.46" *)  _116_;
  assign _114_ = _111_ &(* src = "controlador.v:154.25-154.61" *)  pin_validation;
  assign _109_[0] = _112_ &(* src = "controlador.v:162.21-162.57" *)  pin_validation;
  assign _117_[9] = Y ? (* src = "controlador.v:124.22-124.23|controlador.v:124.18-137.21" *) 1'h0 : _008_[2];
  assign _117_[10] = Y ? (* src = "controlador.v:124.22-124.23|controlador.v:124.18-137.21" *) 1'h0 : _008_[1];
  assign _117_[11] = Y ? (* src = "controlador.v:124.22-124.23|controlador.v:124.18-137.21" *) 1'h1 : _008_[2];
  assign _125_[5] = _114_ ? (* src = "controlador.v:114.22-114.58|controlador.v:114.18-116.21" *) _129_[0] : _004_[0];
  assign _125_[6] = _114_ ? (* src = "controlador.v:114.22-114.58|controlador.v:114.18-116.21" *) _130_[1] : _004_[1];
  assign _125_[7] = _114_ ? (* src = "controlador.v:114.22-114.58|controlador.v:114.18-116.21" *) _130_[2] : _004_[2];
  assign _125_[8] = _114_ ? (* src = "controlador.v:114.22-114.58|controlador.v:114.18-116.21" *) _130_[3] : _004_[3];
  assign _125_[9] = _114_ ? (* src = "controlador.v:114.22-114.58|controlador.v:114.18-116.21" *) _130_[4] : _004_[4];
  assign _004_[0] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : i[0];
  assign _004_[1] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : i[1];
  assign _004_[2] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : i[2];
  assign _004_[3] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : i[3];
  assign _004_[4] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : i[4];
  assign _007_[0] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : _005_[0];
  assign _007_[1] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h1 : _005_[1];
  assign _007_[2] = _109_[0] ? (* src = "controlador.v:109.22-109.58|controlador.v:109.18-113.21" *) 1'h0 : _005_[2];
  assign _117_[15] = _115_ ? (* src = "controlador.v:95.23-95.44|controlador.v:95.19-95.65" *) 1'h1 : _005_[0];
  assign _117_[16] = _115_ ? (* src = "controlador.v:95.23-95.44|controlador.v:95.19-95.65" *) 1'h0 : _005_[1];
  assign _117_[17] = _115_ ? (* src = "controlador.v:95.23-95.44|controlador.v:95.19-95.65" *) 1'h0 : _005_[2];
  assign _005_[0] = Y ? (* src = "controlador.v:82.22-82.23|controlador.v:82.18-88.21" *) 1'h0 : state[0];
  assign _005_[1] = Y ? (* src = "controlador.v:82.22-82.23|controlador.v:82.18-88.21" *) 1'h0 : state[1];
  assign _005_[2] = Y ? (* src = "controlador.v:82.22-82.23|controlador.v:82.18-88.21" *) 1'h1 : state[2];
  assign _117_[12] = _113_ ? (* src = "controlador.v:117.22-117.26|controlador.v:117.18-120.21" *) 1'h1 : _007_[0];
  assign _117_[13] = _113_ ? (* src = "controlador.v:117.22-117.26|controlador.v:117.18-120.21" *) 1'h1 : _007_[1];
  assign _117_[14] = _113_ ? (* src = "controlador.v:117.22-117.26|controlador.v:117.18-120.21" *) 1'h0 : _007_[2];
  assign _002_ = _023_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) 1'h0 : _006_;
  assign _001_ = _021_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10" *) 1'h0 : _006_;
  assign nxt_state[0] = _136_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _120_[0] : 1'h0;
  assign nxt_state[1] = _136_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _120_[1] : 1'h0;
  assign nxt_state[2] = _136_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _120_[2] : 1'h0;
  assign nxt_i[0] = _000_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _127_[0] : 1'hx;
  assign nxt_i[1] = _000_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _127_[1] : 1'hx;
  assign nxt_i[2] = _000_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _127_[2] : 1'hx;
  assign nxt_i[3] = _000_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _127_[3] : 1'hx;
  assign nxt_i[4] = _000_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _127_[4] : 1'hx;
  assign _123_ = _137_ ? (* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _124_ : 1'h0;
  assign _003_[2] = sensor_b ? (* src = "controlador.v:180.27-180.36|controlador.v:180.23-182.40" *) 1'hx : 1'h0;
  assign _117_[1] = Y ? (* src = "controlador.v:169.23-169.24|controlador.v:169.19-183.21" *) 1'h0 : _003_[2];
  assign _117_[2] = Y ? (* src = "controlador.v:169.23-169.24|controlador.v:169.19-183.21" *) 1'h1 : _003_[2];
  assign _117_[3] = _109_[0] ? (* src = "controlador.v:162.21-162.57|controlador.v:162.17-164.21" *) old_state[0] : 1'hx;
  assign _117_[4] = _109_[0] ? (* src = "controlador.v:162.21-162.57|controlador.v:162.17-164.21" *) old_state[1] : 1'hx;
  assign _117_[5] = _109_[0] ? (* src = "controlador.v:162.21-162.57|controlador.v:162.17-164.21" *) old_state[2] : 1'hx;
  assign _009_[2] = _109_[0] ? (* src = "controlador.v:150.25-150.61|controlador.v:150.21-153.24" *) 1'h0 : 1'hx;
  assign _009_[1] = _109_[0] ? (* src = "controlador.v:150.25-150.61|controlador.v:150.21-153.24" *) 1'h1 : 1'hx;
  assign _117_[6] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'h0 : _009_[2];
  assign _117_[7] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'h0 : _009_[1];
  assign _117_[8] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'h1 : _009_[2];
  assign _125_[0] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'hx : _125_[5];
  assign _125_[1] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'hx : _125_[6];
  assign _125_[2] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'hx : _125_[7];
  assign _125_[3] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'hx : _125_[8];
  assign _125_[4] = Y ? (* src = "controlador.v:141.22-141.23|controlador.v:141.18-157.21" *) 1'hx : _125_[9];
  assign _008_[2] = _110_[1] ? (* src = "controlador.v:133.25-133.46|controlador.v:133.21-136.24" *) 1'h1 : 1'hx;
  assign _008_[1] = _110_[1] ? (* src = "controlador.v:133.25-133.46|controlador.v:133.21-136.24" *) 1'h0 : 1'hx;
  assign _020_ = ~(* src = "controlador.v:64.1-191.4" *) _113_;
  assign _024_ = ~(* src = "controlador.v:64.1-191.4" *) _110_[1];
  assign _134_ = ~(* src = "controlador.v:117.22-117.26" *) _135_;
  assign _116_ = ~(* src = "controlador.v:133.37-133.46" *) sensor_a;
  assign _025_ = _018_ &(* src = "controlador.v:64.1-191.4" *)  _019_;
  assign _048_ = _017_ &(* src = "controlador.v:64.1-191.4" *)  _025_;
  assign _026_ = _119_[2] &(* src = "controlador.v:64.1-191.4" *)  Y;
  assign _049_ = _119_[2] &(* src = "controlador.v:64.1-191.4" *)  _026_;
  assign _050_ = _119_[4] &(* src = "controlador.v:64.1-191.4" *)  _020_;
  assign _028_ = _022_ &(* src = "controlador.v:64.1-191.4" *)  _023_;
  assign _030_ = _021_ &(* src = "controlador.v:64.1-191.4" *)  _029_;
  assign _052_ = _119_[2] &(* src = "controlador.v:64.1-191.4" *)  _032_;
  assign _033_ = _006_ &(* src = "controlador.v:64.1-191.4" *)  _024_;
  assign _034_ = _119_[3] &(* src = "controlador.v:64.1-191.4" *)  _033_;
  assign _035_ = _006_ &(* src = "controlador.v:64.1-191.4" *)  _034_;
  assign _036_ = _119_[3] &(* src = "controlador.v:64.1-191.4" *)  _035_;
  assign _053_ = _119_[3] &(* src = "controlador.v:64.1-191.4" *)  _036_;
  assign _029_ = _019_ &(* src = "controlador.v:64.1-191.4" *)  _028_;
  assign _031_ = _018_ &(* src = "controlador.v:64.1-191.4" *)  _030_;
  assign _051_ = _017_ &(* src = "controlador.v:64.1-191.4" *)  _031_;
  assign _054_ = _119_[4] &(* src = "controlador.v:64.1-191.4" *)  _037_;
  assign _055_ = _017_ &(* src = "controlador.v:64.1-191.4" *)  _042_;
  assign _032_ = _119_[2] &(* src = "controlador.v:64.1-191.4" *)  _006_;
  assign _043_ = _119_[3] &(* src = "controlador.v:64.1-191.4" *)  _006_;
  assign _056_ = _119_[3] &(* src = "controlador.v:64.1-191.4" *)  _043_;
  assign _037_ = _119_[4] &(* src = "controlador.v:64.1-191.4" *)  _006_;
  assign _040_ = _019_ &(* src = "controlador.v:64.1-191.4" *)  _023_;
  assign _041_ = _021_ &(* src = "controlador.v:64.1-191.4" *)  _040_;
  assign _042_ = _018_ &(* src = "controlador.v:64.1-191.4" *)  _041_;
  assign _045_ = _119_[0] &(* src = "controlador.v:64.1-191.4" *)  _006_;
  assign _057_ = _119_[0] &(* src = "controlador.v:64.1-191.4" *)  _045_;
  assign _046_ = _119_[5] &(* src = "controlador.v:64.1-191.4" *)  _006_;
  assign _058_ = _119_[5] &(* src = "controlador.v:64.1-191.4" *)  _046_;
  assign _118_[12] = _117_[12] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _118_[13] = _117_[13] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _118_[14] = _117_[14] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _118_[9] = _117_[9] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[3];
  assign _118_[10] = _117_[10] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[3];
  assign _118_[11] = _117_[11] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[3];
  assign _118_[6] = _117_[6] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _118_[7] = _117_[7] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _118_[8] = _117_[8] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _118_[3] = _117_[3] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[1];
  assign _118_[4] = _117_[4] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[1];
  assign _118_[5] = _117_[5] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[1];
  assign _135_ = _133_[31] |(* src = {0{1'b0}} *)  _100_[0];
  assign _126_[5] = _125_[5] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _126_[6] = _125_[6] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _126_[7] = _125_[7] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _126_[8] = _125_[8] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _126_[9] = _125_[9] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[4];
  assign _126_[0] = _125_[0] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _126_[1] = _125_[1] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _126_[2] = _125_[2] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _126_[3] = _125_[3] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _126_[4] = _125_[4] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[2];
  assign _118_[1] = _117_[1] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[0];
  assign _118_[2] = _117_[2] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[0];
  assign _121_[0] = Y &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _122_[0];
  assign _118_[15] = _117_[15] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[5];
  assign _118_[16] = _117_[16] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[5];
  assign _118_[17] = _117_[17] &(* src = "controlador.v:0.0-0.0|controlador.v:80.3-189.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _119_[5];
  assign _130_[1] = i[1] ^(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  i[0];
  assign _130_[2] = i[2] ^(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _128_[1];
  assign _130_[3] = i[3] ^(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _128_[2];
  assign _130_[4] = i[4] ^(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _128_[3];
  assign _139_ = _132_[3] &(* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  i[2];
  assign _098_[1] = _132_[3] &(* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _132_[2];
  assign _140_ = _132_[4] &(* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _131_[3];
  assign _141_ = i[3] |(* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _139_;
  assign _131_[3] = _141_ |(* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _099_[0];
  assign _131_[31] = i[4] |(* src = "controlador.v:117.22-117.26|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _140_;
  assign _128_[3] = _138_ &(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _128_[1];
  assign _138_ = i[3] &(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  i[2];
  assign _128_[2] = i[2] &(* src = "controlador.v:155.31-155.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _128_[1];
  assign Y = sensor_a &(* src = "controlador.v:195.12-195.31" *)  sensor_b;
  assign _003_[1:0] = { _003_[2], _003_[2] };
  assign _008_[0] = _008_[2];
  assign _009_[0] = _009_[2];
  assign _095_[1:0] = _090_;
  assign { _098_[15:2], _098_[0] } = { 13'h1fff, _132_[4], _128_[1] };
  assign _099_[7:1] = { 6'h3f, _132_[4] };
  assign _100_[3:1] = 3'h7;
  assign _109_[1] = _022_;
  assign { _110_[2], _110_[0] } = { _021_, Y };
  assign _117_[0] = _117_[1];
  assign _118_[0] = _118_[1];
  assign _122_[1] = _121_[1];
  assign { _128_[31:5], _128_[0] } = { 27'h0000000, i[0] };
  assign _129_[31:1] = { 27'h0000000, i[4:1] };
  assign { _130_[31:5], _130_[0] } = { 26'h0000000, _128_[4], _129_[0] };
  assign { _131_[30:4], _131_[1:0] } = { _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _131_[31], _128_[1], i[0] };
  assign { _132_[31:5], _132_[1:0] } = { 27'h7ffffff, i[1:0] };
  assign { _133_[30:5], _133_[1:0] } = { _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _130_[1], _129_[0] };
endmodule
