/* Generated by Yosys 0.40+33 (git sha1 c3ae33da3, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

module arbiter(clock, reset, req_0, req_1, gnt_0, gnt_1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  input clock;
  wire clock;
  output gnt_0;
  wire gnt_0;
  output gnt_1;
  wire gnt_1;
  input req_0;
  wire req_0;
  input req_1;
  wire req_1;
  input reset;
  wire reset;
  NOR _24_ (
    .A(req_0),
    .B(req_1),
    .Y(_02_)
  );
  NOT _25_ (
    .A(_02_),
    .Y(_00_)
  );
  NOR _26_ (
    .A(req_0),
    .B(reset),
    .Y(_03_)
  );
  NOT _27_ (
    .A(_03_),
    .Y(_01_)
  );
  BUF _28_ (
    .A(req_0),
    .Y(_04_)
  );
  NOT _29_ (
    .A(_10_),
    .Y(_12_)
  );
  NAND _30_ (
    .A(_07_),
    .B(_05_),
    .Y(_13_)
  );
  NOT _31_ (
    .A(_13_),
    .Y(_14_)
  );
  NOR _32_ (
    .A(_12_),
    .B(_05_),
    .Y(_15_)
  );
  NOR _33_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _34_ (
    .A(_19_),
    .B(_16_),
    .Y(_08_)
  );
  NOR _35_ (
    .A(_11_),
    .B(_18_),
    .Y(_17_)
  );
  NOR _36_ (
    .A(_06_),
    .B(_17_),
    .Y(_09_)
  );
  DFF _37_ (
    .C(clock),
    .D(_21_),
    .Q(gnt_0)
  );
  DFF _38_ (
    .C(clock),
    .D(_23_),
    .Q(gnt_1)
  );
  assign _10_ = gnt_0;
  assign _07_ = _04_;
  assign _05_ = _00_;
  assign _11_ = gnt_1;
  assign _18_ = req_1;
  assign _19_ = reset;
  assign _21_ = _08_;
  assign _06_ = _01_;
  assign _23_ = _09_;
endmodule
