/* Generated by Yosys 0.40+33 (git sha1 c3ae33da3, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "controlador.v:8.1-228.10" *)
module controlador(clock, reset, sensor_a, sensor_b, pin_validation, pin, alarma_pin_incorrecto, alarma_bloqueo, senal_abrir_compuerta, senal_cerrar_compuerta);
  (* src = "controlador.v:83.1-222.4" *)
  wire [2:0] _000_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [2:0] _001_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [4:0] _002_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [2:0] _003_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [1:0] _004_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [4:0] _005_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [1:0] _006_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [2:0] _007_;
  (* src = "controlador.v:83.1-222.4" *)
  wire [2:0] _008_;
  (* src = "controlador.v:26.35-26.49" *)
  wire _009_;
  (* src = "controlador.v:26.12-26.33" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  (* src = "controlador.v:41.11-41.12" *)
  wire _026_;
  (* src = "controlador.v:41.11-41.12" *)
  wire _027_;
  (* src = "controlador.v:41.11-41.12" *)
  wire _028_;
  (* src = "controlador.v:41.11-41.12" *)
  wire _029_;
  (* src = "controlador.v:41.11-41.12" *)
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  (* src = "controlador.v:35.11-35.20" *)
  wire _180_;
  (* src = "controlador.v:35.11-35.20" *)
  wire _181_;
  (* src = "controlador.v:35.11-35.20" *)
  wire _182_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _183_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _184_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _185_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _186_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _187_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _188_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _189_;
  (* src = "controlador.v:23.13-23.16" *)
  wire _190_;
  (* src = "controlador.v:22.41-22.55" *)
  wire _191_;
  (* src = "controlador.v:22.14-22.19" *)
  wire _192_;
  (* src = "controlador.v:27.12-27.33" *)
  wire _193_;
  (* src = "controlador.v:27.35-27.57" *)
  wire _194_;
  (* src = "controlador.v:22.21-22.29" *)
  wire _195_;
  (* src = "controlador.v:22.31-22.39" *)
  wire _196_;
  (* src = "controlador.v:32.11-32.16" *)
  wire _197_;
  (* src = "controlador.v:32.11-32.16" *)
  wire _198_;
  (* src = "controlador.v:32.11-32.16" *)
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire [1:0] _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire [15:0] _276_;
  wire [7:0] _277_;
  wire [3:0] _278_;
  wire _279_;
  wire [1:0] _280_;
  wire [1:0] _281_;
  wire _282_;
  wire _283_;
  wire [2:0] _284_;
  wire _285_;
  wire [2:0] _286_;
  wire _287_;
  wire [2:0] _288_;
  wire _289_;
  wire [2:0] _290_;
  wire _291_;
  wire [3:0] _292_;
  wire [1:0] _293_;
  wire _294_;
  wire _295_;
  wire [1:0] _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire [1:0] _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire [1:0] _306_;
  wire [2:0] _307_;
  wire [2:0] _308_;
  wire _309_;
  (* src = "controlador.v:138.26-138.44" *)
  wire _310_;
  (* src = "controlador.v:142.26-142.62" *)
  wire _311_;
  (* src = "controlador.v:164.37-164.46" *)
  wire _312_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [5:0] _313_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [5:0] _314_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _315_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _316_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [5:0] _317_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _318_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _319_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [7:0] _320_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [7:0] _321_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _322_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _323_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [5:0] _324_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [5:0] _325_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _326_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _327_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [17:0] _328_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [17:0] _329_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _330_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:186.31-186.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _331_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:186.31-186.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _332_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:186.31-186.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _333_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:145.26-145.30|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _334_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:145.26-145.30|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _335_;
  (* force_downto = 32'd1 *)
  (* src = "controlador.v:145.26-145.30|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4" *)
  wire [31:0] _336_;
  wire _337_;
  wire _338_;
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _339_;
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _340_;
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _341_;
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _342_;
  (* src = "controlador.v:0.0-0.0|controlador.v:103.3-220.10|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _343_;
  (* src = "controlador.v:186.31-186.36|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _344_;
  (* src = "controlador.v:145.26-145.30|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _345_;
  (* src = "controlador.v:145.26-145.30|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _346_;
  (* src = "controlador.v:145.26-145.30|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alonsojose/Documents/Programs/Yosys/oss-cad-suite-linux-x64-20240425/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _347_;
  (* src = "controlador.v:57.6-57.7" *)
  wire Y;
  (* src = "controlador.v:26.35-26.49" *)
  output alarma_bloqueo;
  wire alarma_bloqueo;
  (* src = "controlador.v:26.12-26.33" *)
  output alarma_pin_incorrecto;
  wire alarma_pin_incorrecto;
  (* src = "controlador.v:22.7-22.12" *)
  input clock;
  wire clock;
  (* src = "controlador.v:41.11-41.12" *)
  wire [4:0] i;
  (* src = "controlador.v:51.11-51.30" *)
  wire [1:0] next_alarma_bloqueo;
  (* src = "controlador.v:50.11-50.37" *)
  wire [1:0] next_alarma_pin_incorrecto;
  (* src = "controlador.v:52.11-52.37" *)
  wire [1:0] next_senal_abrir_compuerta;
  (* src = "controlador.v:53.11-53.38" *)
  wire [1:0] next_senal_cerrar_compuerta;
  (* src = "controlador.v:44.11-44.20" *)
  wire [2:0] nxt_state;
  (* src = "controlador.v:35.11-35.20" *)
  wire [2:0] old_state;
  (* src = "controlador.v:23.13-23.16" *)
  input [7:0] pin;
  wire [7:0] pin;
  (* src = "controlador.v:22.41-22.55" *)
  input pin_validation;
  wire pin_validation;
  (* src = "controlador.v:22.14-22.19" *)
  input reset;
  wire reset;
  (* src = "controlador.v:27.12-27.33" *)
  output senal_abrir_compuerta;
  wire senal_abrir_compuerta;
  (* src = "controlador.v:27.35-27.57" *)
  output senal_cerrar_compuerta;
  wire senal_cerrar_compuerta;
  (* src = "controlador.v:22.21-22.29" *)
  input sensor_a;
  wire sensor_a;
  (* src = "controlador.v:22.31-22.39" *)
  input sensor_b;
  wire sensor_b;
  (* src = "controlador.v:32.11-32.16" *)
  wire [2:0] state;
  NOT _348_ (
    .A(_030_),
    .Y(_126_)
  );
  NOT _349_ (
    .A(_028_),
    .Y(_127_)
  );
  NOT _350_ (
    .A(_027_),
    .Y(_128_)
  );
  NOT _351_ (
    .A(_199_),
    .Y(_129_)
  );
  NOT _352_ (
    .A(_198_),
    .Y(_130_)
  );
  NOT _353_ (
    .A(_197_),
    .Y(_131_)
  );
  NOT _354_ (
    .A(_180_),
    .Y(_132_)
  );
  NOT _355_ (
    .A(_192_),
    .Y(_133_)
  );
  NOT _356_ (
    .A(_183_),
    .Y(_134_)
  );
  NOT _357_ (
    .A(_196_),
    .Y(_135_)
  );
  NOT _358_ (
    .A(_184_),
    .Y(_136_)
  );
  NOT _359_ (
    .A(_191_),
    .Y(_137_)
  );
  NAND _360_ (
    .A(_196_),
    .B(_195_),
    .Y(_138_)
  );
  NOT _361_ (
    .A(_138_),
    .Y(_139_)
  );
  NOR _362_ (
    .A(_199_),
    .B(_138_),
    .Y(_140_)
  );
  NOR _363_ (
    .A(_198_),
    .B(_131_),
    .Y(_141_)
  );
  NAND _364_ (
    .A(_130_),
    .B(_197_),
    .Y(_142_)
  );
  NOR _365_ (
    .A(_138_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _366_ (
    .A(_129_),
    .B(_142_),
    .Y(_144_)
  );
  NAND _367_ (
    .A(_199_),
    .B(_141_),
    .Y(_145_)
  );
  NOR _368_ (
    .A(_129_),
    .B(_141_),
    .Y(_146_)
  );
  NOR _369_ (
    .A(_140_),
    .B(_143_),
    .Y(_147_)
  );
  NOR _370_ (
    .A(_138_),
    .B(_146_),
    .Y(_148_)
  );
  NAND _371_ (
    .A(_180_),
    .B(_147_),
    .Y(_149_)
  );
  NOR _372_ (
    .A(_129_),
    .B(_130_),
    .Y(_150_)
  );
  NAND _373_ (
    .A(_199_),
    .B(_198_),
    .Y(_151_)
  );
  NOR _374_ (
    .A(_138_),
    .B(_150_),
    .Y(_152_)
  );
  NAND _375_ (
    .A(_197_),
    .B(_152_),
    .Y(_153_)
  );
  NAND _376_ (
    .A(_149_),
    .B(_153_),
    .Y(_154_)
  );
  NOT _377_ (
    .A(_154_),
    .Y(_155_)
  );
  NOR _378_ (
    .A(_192_),
    .B(_155_),
    .Y(_011_)
  );
  NAND _379_ (
    .A(_181_),
    .B(_147_),
    .Y(_156_)
  );
  NAND _380_ (
    .A(_198_),
    .B(_140_),
    .Y(_157_)
  );
  NAND _381_ (
    .A(_156_),
    .B(_157_),
    .Y(_158_)
  );
  NOT _382_ (
    .A(_158_),
    .Y(_159_)
  );
  NOR _383_ (
    .A(_192_),
    .B(_159_),
    .Y(_012_)
  );
  NOR _384_ (
    .A(_182_),
    .B(_143_),
    .Y(_160_)
  );
  NOR _385_ (
    .A(_192_),
    .B(_140_),
    .Y(_161_)
  );
  NOT _386_ (
    .A(_161_),
    .Y(_162_)
  );
  NOR _387_ (
    .A(_160_),
    .B(_162_),
    .Y(_013_)
  );
  NOR _388_ (
    .A(_199_),
    .B(_139_),
    .Y(_163_)
  );
  NAND _389_ (
    .A(_129_),
    .B(_138_),
    .Y(_164_)
  );
  NAND _390_ (
    .A(_027_),
    .B(_026_),
    .Y(_165_)
  );
  NOT _391_ (
    .A(_165_),
    .Y(_166_)
  );
  NOR _392_ (
    .A(_030_),
    .B(_029_),
    .Y(_167_)
  );
  NOT _393_ (
    .A(_167_),
    .Y(_168_)
  );
  NOR _394_ (
    .A(_028_),
    .B(_168_),
    .Y(_169_)
  );
  NAND _395_ (
    .A(_127_),
    .B(_167_),
    .Y(_170_)
  );
  NOR _396_ (
    .A(_166_),
    .B(_170_),
    .Y(_171_)
  );
  NAND _397_ (
    .A(_165_),
    .B(_169_),
    .Y(_172_)
  );
  NAND _398_ (
    .A(_141_),
    .B(_171_),
    .Y(_173_)
  );
  NAND _399_ (
    .A(_163_),
    .B(_173_),
    .Y(_174_)
  );
  NAND _400_ (
    .A(_010_),
    .B(_174_),
    .Y(_175_)
  );
  NOT _401_ (
    .A(_175_),
    .Y(_176_)
  );
  NOR _402_ (
    .A(_131_),
    .B(_164_),
    .Y(_177_)
  );
  NAND _403_ (
    .A(_197_),
    .B(_163_),
    .Y(_178_)
  );
  NOR _404_ (
    .A(_198_),
    .B(_172_),
    .Y(_179_)
  );
  NOR _405_ (
    .A(_178_),
    .B(_179_),
    .Y(_031_)
  );
  NOR _406_ (
    .A(_176_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _407_ (
    .A(_192_),
    .B(_032_),
    .Y(_014_)
  );
  NOR _408_ (
    .A(_150_),
    .B(_177_),
    .Y(_033_)
  );
  NAND _409_ (
    .A(_151_),
    .B(_178_),
    .Y(_034_)
  );
  NOR _410_ (
    .A(_130_),
    .B(_197_),
    .Y(_035_)
  );
  NAND _411_ (
    .A(_198_),
    .B(_131_),
    .Y(_036_)
  );
  NOR _412_ (
    .A(_199_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _413_ (
    .A(_199_),
    .B(_196_),
    .Y(_038_)
  );
  NAND _414_ (
    .A(_035_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _415_ (
    .A(_033_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _416_ (
    .A(_009_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _417_ (
    .A(_198_),
    .B(_197_),
    .Y(_042_)
  );
  NAND _418_ (
    .A(_199_),
    .B(_042_),
    .Y(_043_)
  );
  NOT _419_ (
    .A(_043_),
    .Y(_044_)
  );
  NAND _420_ (
    .A(_041_),
    .B(_043_),
    .Y(_045_)
  );
  NOR _421_ (
    .A(_152_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _422_ (
    .A(_192_),
    .B(_046_),
    .Y(_015_)
  );
  NAND _423_ (
    .A(_193_),
    .B(_034_),
    .Y(_047_)
  );
  NAND _424_ (
    .A(_138_),
    .B(_037_),
    .Y(_048_)
  );
  NAND _425_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOT _426_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _427_ (
    .A(_192_),
    .B(_050_),
    .Y(_016_)
  );
  NAND _428_ (
    .A(_129_),
    .B(_042_),
    .Y(_051_)
  );
  NAND _429_ (
    .A(_194_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _430_ (
    .A(_145_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _431_ (
    .A(_133_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _432_ (
    .A(_148_),
    .B(_054_),
    .Y(_017_)
  );
  NOR _433_ (
    .A(_134_),
    .B(_184_),
    .Y(_055_)
  );
  NAND _434_ (
    .A(_183_),
    .B(_136_),
    .Y(_056_)
  );
  NOR _435_ (
    .A(_189_),
    .B(_190_),
    .Y(_057_)
  );
  NOT _436_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _437_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _438_ (
    .A(_055_),
    .B(_057_),
    .Y(_060_)
  );
  NAND _439_ (
    .A(_187_),
    .B(_188_),
    .Y(_061_)
  );
  NAND _440_ (
    .A(_186_),
    .B(_185_),
    .Y(_062_)
  );
  NOR _441_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NOT _442_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR _443_ (
    .A(_060_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _444_ (
    .A(_059_),
    .B(_063_),
    .Y(_066_)
  );
  NOR _445_ (
    .A(_137_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _446_ (
    .A(_191_),
    .B(_065_),
    .Y(_068_)
  );
  NOR _447_ (
    .A(_132_),
    .B(_043_),
    .Y(_069_)
  );
  NAND _448_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _449_ (
    .A(_142_),
    .B(_164_),
    .Y(_071_)
  );
  NAND _450_ (
    .A(_130_),
    .B(_177_),
    .Y(_072_)
  );
  NAND _451_ (
    .A(_172_),
    .B(_071_),
    .Y(_073_)
  );
  NAND _452_ (
    .A(_070_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _453_ (
    .A(_177_),
    .B(_068_),
    .Y(_075_)
  );
  NOR _454_ (
    .A(_135_),
    .B(_195_),
    .Y(_076_)
  );
  NAND _455_ (
    .A(_196_),
    .B(_037_),
    .Y(_077_)
  );
  NOT _456_ (
    .A(_077_),
    .Y(_078_)
  );
  NOR _457_ (
    .A(_195_),
    .B(_077_),
    .Y(_079_)
  );
  NAND _458_ (
    .A(_144_),
    .B(_076_),
    .Y(_080_)
  );
  NAND _459_ (
    .A(_038_),
    .B(_042_),
    .Y(_081_)
  );
  NOT _460_ (
    .A(_081_),
    .Y(_082_)
  );
  NAND _461_ (
    .A(_195_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _462_ (
    .A(_080_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _463_ (
    .A(_079_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _464_ (
    .A(_075_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _465_ (
    .A(_074_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _466_ (
    .A(_192_),
    .B(_087_),
    .Y(_018_)
  );
  NAND _467_ (
    .A(_181_),
    .B(_044_),
    .Y(_088_)
  );
  NAND _468_ (
    .A(_072_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _469_ (
    .A(_067_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _470_ (
    .A(_039_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _471_ (
    .A(_031_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _472_ (
    .A(_192_),
    .B(_092_),
    .Y(_019_)
  );
  NOR _473_ (
    .A(_182_),
    .B(_068_),
    .Y(_093_)
  );
  NOR _474_ (
    .A(_043_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _475_ (
    .A(_147_),
    .B(_035_),
    .Y(_095_)
  );
  NOR _476_ (
    .A(_078_),
    .B(_095_),
    .Y(_096_)
  );
  NAND _477_ (
    .A(_080_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _478_ (
    .A(_094_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _479_ (
    .A(_192_),
    .B(_098_),
    .Y(_020_)
  );
  NOR _480_ (
    .A(_137_),
    .B(_178_),
    .Y(_099_)
  );
  NAND _481_ (
    .A(_191_),
    .B(_177_),
    .Y(_100_)
  );
  NOR _482_ (
    .A(_065_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _483_ (
    .A(_066_),
    .B(_099_),
    .Y(_102_)
  );
  NOR _484_ (
    .A(_026_),
    .B(_101_),
    .Y(_103_)
  );
  NAND _485_ (
    .A(_026_),
    .B(_099_),
    .Y(_104_)
  );
  NAND _486_ (
    .A(_133_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _487_ (
    .A(_103_),
    .B(_105_),
    .Y(_021_)
  );
  NAND _488_ (
    .A(_128_),
    .B(_104_),
    .Y(_106_)
  );
  NOR _489_ (
    .A(_166_),
    .B(_065_),
    .Y(_107_)
  );
  NOR _490_ (
    .A(_100_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _491_ (
    .A(_133_),
    .B(_106_),
    .Y(_109_)
  );
  NOR _492_ (
    .A(_108_),
    .B(_109_),
    .Y(_022_)
  );
  NOR _493_ (
    .A(_127_),
    .B(_108_),
    .Y(_110_)
  );
  NAND _494_ (
    .A(_127_),
    .B(_166_),
    .Y(_111_)
  );
  NOR _495_ (
    .A(_102_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _496_ (
    .A(_110_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _497_ (
    .A(_192_),
    .B(_113_),
    .Y(_023_)
  );
  NAND _498_ (
    .A(_028_),
    .B(_166_),
    .Y(_114_)
  );
  NOR _499_ (
    .A(_100_),
    .B(_114_),
    .Y(_115_)
  );
  NAND _500_ (
    .A(_029_),
    .B(_115_),
    .Y(_116_)
  );
  NOR _501_ (
    .A(_178_),
    .B(_068_),
    .Y(_117_)
  );
  NOR _502_ (
    .A(_192_),
    .B(_117_),
    .Y(_118_)
  );
  NOT _503_ (
    .A(_118_),
    .Y(_119_)
  );
  NOR _504_ (
    .A(_029_),
    .B(_115_),
    .Y(_120_)
  );
  NOT _505_ (
    .A(_120_),
    .Y(_121_)
  );
  NAND _506_ (
    .A(_116_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _507_ (
    .A(_119_),
    .B(_122_),
    .Y(_024_)
  );
  NOR _508_ (
    .A(_126_),
    .B(_116_),
    .Y(_123_)
  );
  NAND _509_ (
    .A(_126_),
    .B(_116_),
    .Y(_124_)
  );
  NAND _510_ (
    .A(_118_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _511_ (
    .A(_123_),
    .B(_125_),
    .Y(_025_)
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _512_ (
    .C(clock),
    .D(_240_),
    .Q(old_state[0])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _513_ (
    .C(clock),
    .D(_242_),
    .Q(old_state[1])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _514_ (
    .C(clock),
    .D(_244_),
    .Q(old_state[2])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _515_ (
    .C(clock),
    .D(_246_),
    .Q(alarma_pin_incorrecto)
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _516_ (
    .C(clock),
    .D(_248_),
    .Q(alarma_bloqueo)
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _517_ (
    .C(clock),
    .D(_250_),
    .Q(senal_abrir_compuerta)
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _518_ (
    .C(clock),
    .D(_252_),
    .Q(senal_cerrar_compuerta)
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _519_ (
    .C(clock),
    .D(_254_),
    .Q(state[0])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _520_ (
    .C(clock),
    .D(_256_),
    .Q(state[1])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _521_ (
    .C(clock),
    .D(_258_),
    .Q(state[2])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _522_ (
    .C(clock),
    .D(_260_),
    .Q(i[0])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _523_ (
    .C(clock),
    .D(_262_),
    .Q(i[1])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _524_ (
    .C(clock),
    .D(_264_),
    .Q(i[2])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _525_ (
    .C(clock),
    .D(_266_),
    .Q(i[3])
  );
  (* src = "controlador.v:61.1-79.4" *)
  DFF _526_ (
    .C(clock),
    .D(_268_),
    .Q(i[4])
  );
  assign _001_[1:0] = { _001_[2], _001_[2] };
  assign _002_[3:0] = { _002_[4], _002_[4], _002_[4], _002_[4] };
  assign _003_[2:1] = 2'h0;
  assign _004_[1] = 1'h0;
  assign _006_[1] = 1'h0;
  assign _008_[1:0] = { _006_[0], _008_[2] };
  assign { _276_[15:2], _276_[0] } = { 13'h1fff, _335_[4], _331_[1] };
  assign _277_[7:1] = { 6'h3f, _335_[4] };
  assign _278_[3:1] = 3'h7;
  assign _281_[0] = _318_[0];
  assign _286_[2] = _329_[13];
  assign _290_[1] = _274_;
  assign _306_[1] = _233_;
  assign { _307_[2], _307_[0] } = { _231_, Y };
  assign { _308_[2], _308_[0] } = { _237_, Y };
  assign { _313_[5:3], _313_[1] } = 4'h0;
  assign { _314_[5:3], _314_[1] } = 4'h0;
  assign _316_[1] = 1'h0;
  assign { _317_[5], _317_[3], _317_[1:0] } = 4'h0;
  assign _319_[1] = 1'h0;
  assign { _320_[7], _320_[5], _320_[3:0] } = { 5'h02, Y };
  assign { _321_[7], _321_[5], _321_[3], _321_[1] } = 4'h0;
  assign _322_[3:1] = { _318_[2:1], _321_[2] };
  assign _323_[1] = 1'h0;
  assign { _324_[5], _324_[3], _324_[1] } = 3'h0;
  assign { _325_[5], _325_[3], _325_[1] } = 3'h0;
  assign _327_[1] = 1'h0;
  assign { _328_[17:16], _328_[0] } = { Y, 1'h0, _328_[1] };
  assign { _329_[16], _329_[0] } = { 1'h0, _329_[1] };
  assign { _331_[31:5], _331_[0] } = { 27'h0000000, i[0] };
  assign _332_[31:1] = { 27'h0000000, i[4:1] };
  assign { _333_[31:5], _333_[0] } = { 26'h0000000, _331_[4], _332_[0] };
  assign { _334_[30:4], _334_[1:0] } = { _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _334_[31], _331_[1], i[0] };
  assign { _335_[31:5], _335_[1:0] } = { 27'h7ffffff, i[1:0] };
  assign { _336_[30:5], _336_[1:0] } = { _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _336_[31], _333_[1], _332_[0] };
  assign next_alarma_bloqueo[1] = 1'h0;
  assign next_alarma_pin_incorrecto[1] = 1'h0;
  assign next_senal_abrir_compuerta[1] = 1'h0;
  assign next_senal_cerrar_compuerta[1] = 1'h0;
  assign _030_ = i[4];
  assign _029_ = i[3];
  assign _028_ = i[2];
  assign _027_ = i[1];
  assign _026_ = i[0];
  assign _199_ = state[2];
  assign _198_ = state[1];
  assign _197_ = state[0];
  assign _194_ = senal_cerrar_compuerta;
  assign _193_ = senal_abrir_compuerta;
  assign _009_ = alarma_bloqueo;
  assign _010_ = alarma_pin_incorrecto;
  assign _182_ = old_state[2];
  assign _181_ = old_state[1];
  assign _180_ = old_state[0];
  assign _192_ = reset;
  assign _240_ = _011_;
  assign _242_ = _012_;
  assign _244_ = _013_;
  assign _246_ = _014_;
  assign _248_ = _015_;
  assign _250_ = _016_;
  assign _252_ = _017_;
  assign _254_ = _018_;
  assign _256_ = _019_;
  assign _258_ = _020_;
  assign _260_ = _021_;
  assign _262_ = _022_;
  assign _264_ = _023_;
  assign _266_ = _024_;
  assign _268_ = _025_;
  assign _187_ = pin[4];
  assign _188_ = pin[5];
  assign _186_ = pin[3];
  assign _185_ = pin[2];
  assign _183_ = pin[0];
  assign _196_ = sensor_b;
  assign _184_ = pin[1];
  assign _189_ = pin[6];
  assign _190_ = pin[7];
  assign _195_ = sensor_a;
  assign _191_ = pin_validation;
endmodule
