tarea:  
	cd transmisor/ && iverilog -o salida testbench.v && vvp salida && gtkwave ondas.gtkw #prueba1
	cd sincronizador/ && iverilog -o salida testbench_sync.v && vvp salida && gtkwave sync_waves.gtkw #prueba2
	cd receptor/ && iverilog -o salida testbench.v && vvp salida && gtkwave waves.gtkw #prueba3
	cd PCS/ && iverilog -o salida testbench.v && vvp salida && gtkwave waves.gtkw #prueba4